#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Master Script: Run Complete Analysis Pipeline (Plan B - P0+P1)

This script runs all core and enhanced analyses in the correct sequence.
Generates all tables and figures needed for a top-tier economics journal submission.

Sequence:
    Phase 1: Data Processing (01-10)
    Phase 2: Enhanced Descriptives (11)  [NEW]
    Phase 3: OLS Baseline (15)  [NEW]
    Phase 4: Core Models (20, 30)
    Phase 5: MCMC Diagnostics (21)  [NEW]
    Phase 6: Model Comparison (22)  [NEW]
    Phase 7: Robustness (robustness/)
    Phase 8: Visualization (31)  [NEW]

Usage:
    python src/00_run_complete_analysis.py

    # Or run specific phases:
    python src/00_run_complete_analysis.py --phase 3

Author: Generated by Antigravity
Date: 2025-12-16
"""

from __future__ import annotations
import subprocess
import sys
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"


def run_script(script_name: str, description: str):
    """Run a Python script and handle errors"""
    script_path = SRC / script_name

    if not script_path.exists():
        print(f"  ⚠ SKIP: {script_name} (file not found)")
        return False

    print(f"\n{'='*70}")
    print(f"  RUNNING: {description}")
    print(f"  Script: {script_name}")
    print(f"{'='*70}")

    try:
        subprocess.check_call([sys.executable, str(script_path)], cwd=str(ROOT))
        print(f"  ✓ SUCCESS: {description}\n")
        return True
    except subprocess.CalledProcessError as e:
        print(f"  ✗ ERROR: {description}")
        print(f"    Return code: {e.returncode}")
        print(f"    Consider running manually: python {script_path}\n")
        return False


def main():
    parser = argparse.ArgumentParser(description='Run complete analysis pipeline')
    parser.add_argument('--phase', type=int, choices=range(1, 9),
                       help='Run specific phase only (1-8)')
    parser.add_argument('--skip-download', action='store_true',
                       help='Skip data download steps (01-04)')
    parser.add_argument('--skip-robustness', action='store_true',
                       help='Skip robustness checks (saves time)')
    args = parser.parse_args()

    phases = {
        1: [
            ("01_download_gpr.py", "Download GPR data"),
            ("02_download_epu.py", "Download EPU data"),
            ("03_scrape_pboc_depositor_survey_extended.py", "Scrape PBOC survey"),
            ("04_download_nbs_easyquery.py", "Download NBS macro data"),
        ],
        2: [
            ("05_carlson_parkin_quantify.py", "Carlson-Parkin quantification"),
            ("06_process_epu.py", "Process EPU data"),
            ("07_process_gpr.py", "Process GPR data"),
            ("08_process_nbs_macro_control.py", "Process NBS controls"),
            ("09_process_food_cpi.py", "Process Food CPI"),
            ("10_build_quarterly_panel.py", "Build quarterly panel"),
        ],
        3: [
            ("11_enhanced_descriptive_stats.py", "Enhanced Descriptive Statistics [P1]"),
            ("12_coupling_bias_check.py", "Mechanical Coupling Bias Check [P1]"),
        ],
        4: [
            ("15_baseline_ols_regression.py", "OLS Baseline Regression [P0]"),
        ],
        5: [
            ("20_bayes_state_space_diagnostic.py", "TVP-SSM Bayesian Estimation"),
            ("30_bvar_sign_restrictions.py", "BVAR with Sign Restrictions"),
        ],
        6: [
            ("21_ssm_mcmc_diagnostics.py", "MCMC Convergence Diagnostics [P0]"),
        ],
        7: [
            ("22_model_comparison.py", "Model Comparison (DIC/WAIC/BF) [P0]"),
        ],
        8: [
            ("robustness/run_robustness.py", "Robustness Checks"),
            ("31_robustness_visualization.py", "Robustness Visualization [P1/P2]"),
        ],
    }

    print("""
╔══════════════════════════════════════════════════════════════╗
║                COMPLETE ANALYSIS PIPELINE                    ║
╚══════════════════════════════════════════════════════════════╝
    """)

    # Determine which phases to run
    if args.phase:
        phases_to_run = {args.phase: phases[args.phase]}
        print(f"Running Phase {args.phase} only\n")
    else:
        phases_to_run = phases.copy()
        if args.skip_download:
            print("Skipping Phase 1 (data download)\n")
            phases_to_run.pop(1, None)
        if args.skip_robustness:
            print("Skipping robustness checks\n")
            phases_to_run.pop(8, None)

    # Track results
    results = {'success': [], 'failed': [], 'skipped': []}

    # Run phases
    for phase_num in sorted(phases_to_run.keys()):
        phase_scripts = phases_to_run[phase_num]

        print(f"\n{'#'*70}")
        print(f"# PHASE {phase_num}")
        print(f"{'#'*70}")

        for script, desc in phase_scripts:
            success = run_script(script, desc)
            if success:
                results['success'].append((script, desc))
            elif success is False:
                results['failed'].append((script, desc))
            else:
                results['skipped'].append((script, desc))

    # Final summary
    print(f"\n{'='*70}")
    print("PIPELINE COMPLETE - SUMMARY")
    print(f"{'='*70}")

    print(f"\n✓ SUCCESS: {len(results['success'])} scripts")
    for script, desc in results['success']:
        print(f"  - {desc}")

    if results['failed']:
        print(f"\n✗ FAILED: {len(results['failed'])} scripts")
        for script, desc in results['failed']:
            print(f"  - {desc} ({script})")

    if results['skipped']:
        print(f"\n⚠ SKIPPED: {len(results['skipped'])} scripts")
        for script, desc in results['skipped']:
            print(f"  - {desc}")

    # Output file summary
    print(f"\n{'='*70}")
    print("KEY OUTPUTS GENERATED")
    print(f"{'='*70}")

    tables_dir = ROOT / "outputs" / "tables"
    figures_dir = ROOT / "outputs" / "figures"

    print("\n📊 TABLES:")
    if tables_dir.exists():
        for tex_file in sorted(tables_dir.glob("*.tex")):
            priority = ""
            if any(x in tex_file.stem for x in ["ols_baseline", "mcmc_diag", "model_comp"]):
                priority = " [P0 ⭐]"
            elif any(x in tex_file.stem for x in ["fe_fr", "fevd", "historical"]):
                priority = " [P1]"
            print(f"  - {tex_file.name}{priority}")

    print("\n📈 FIGURES:")
    if figures_dir.exists():
        for fig_file in sorted(figures_dir.glob("*.png")):
            priority = ""
            if "mcmc" in fig_file.stem:
                priority = " [P0]"
            elif any(x in fig_file.stem for x in ["robustness", "sensitivity"]):
                priority = " [P1/P2]"
            print(f"  - {fig_file.name}{priority}")

    print(f"\n{'='*70}")
    print("NEXT STEPS")
    print(f"{'='*70}")
    print("""
1. Review outputs/tables/ for LaTeX tables
2. Include figures from outputs/figures/ in your paper
3. Update Draft v1.1-Complete.md with new table numbers
4. Compile LaTeX to verify all tables work
5. Check MCMC diagnostics (mcmc_diagnostics.tex) - all parameters converged?
6. Verify model comparison (model_comparison.tex) - TVP > fixed-beta?
7. Review OLS baseline (ols_baseline.tex) - beta < 0 and significant?

If any scripts failed, run them individually to debug:
    python src/SCRIPT_NAME.py
    """)

    # Exit code
    if results['failed']:
        print("\n⚠ WARNING: Some scripts failed. Review errors above.")
        sys.exit(1)
    else:
        print("\n✓ ALL SCRIPTS COMPLETED SUCCESSFULLY!")
        sys.exit(0)


if __name__ == '__main__':
    main()
